name: Build & Deploy to AWS EC2
run-name: Build & Deploy to AWS EC2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the project
        uses: actions/checkout@v4

      - name: Show project dir
        run: ls -lha

      - name: Archieve artifact
        run: mkdir -p ./artifact && cd build && tar -zcf ../artifact/${{ github.sha }}.tar.gz .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-build
          path: artifact

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: html-build
          path: artifact

      - name: Show dir
        run: pwd && ls -lha