name: Build & Deploy to AWS EC2
run-name: Build & Deploy to AWS EC2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the project
        uses: actions/checkout@v4

      - name: Show project dir
        run: ls -lha

      - name: Archieve artifact
        run: mkdir -p ./artifact && cd build && tar -zcf ../artifact/${{ github.sha }}.tar.gz .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-build
          path: artifact

  deploy:
    need: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: html-build
          path: artifact

      - name: Show dir
        run: pwd && ls -lha

      - name: Install AWS CLI
        run: sudo apt install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-west-1

      - name: Write private key to file
        run: |
          mkdir ~/.ssh/
          echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Fetch EC2 IP
        run: |
          IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=nginx" --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          echo "IP: ${IP}"