name: First workflow
run-name: First workflow

on:
  push:
    branch:
      - new_feature

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: First listing
      run: |
        pwd
        ls -lha

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Second listing
      run: |
        pwd
        ls -lha
