name: Matrix

on:
  push:
    branch:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check node JS version and OS dist
      run: |
        echo "nodeJS version: ${{ matrix.node-version }}"
        echo "OS dist: ${{ matrix.os }}"